CREATE TABLE MOVIE
(
  ID INTEGER GENERATED ALWAYS AS IDENTITY MINVALUE 1000 MAXVALUE 9999 INCREMENT BY 1,
  Titulo VARCHAR2(250) NOT NULL,
  Director VARCHAR2(100) NOT NULL,
  Anho INTEGER,
  Duracion INTEGER,
  Genero VARCHAR2(30)
);




