/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.prueba3.view;

import com.mycompany.prueba3.controller.ConectorBD;
import com.mycompany.prueba3.controller.PeliculaController;
import com.mycompany.prueba3.model.MovieDAO;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author tomac
 */
public class Inicio extends javax.swing.JFrame {
private TableRowSorter trsfFiltro;
    /**
     * Creates new form Inicio
     */
    public Inicio() throws SQLException{
        initComponents();
        this.conector = new ConectorBD();
        this.conector.crearConexion();
        //cargarTabla();
    } 
 
     public void filtro() {
        int columnaGenero = 5;
        int columnaAnho = 3;
        int anhoFiltro = 1900;
        int anhoFiltro2 = 2023;
        
        if(!jTextFieldAnhoFiltro1.getText().isEmpty()){
            anhoFiltro = Integer.parseInt(jTextFieldAnhoFiltro1.getText());
        }
        if(!jTextFieldAnhoFiltro2.getText().isEmpty()){
            anhoFiltro2 = Integer.parseInt(jTextFieldAnhoFiltro2.getText());
        }
        
        
        List<RowFilter<Object , Object>> filters = new ArrayList<RowFilter<Object , Object>>();
        filters.add(RowFilter.regexFilter(jTextFieldFiltro.getText(), columnaGenero));
        filters.add(RowFilter.numberFilter(RowFilter.ComparisonType.AFTER, anhoFiltro -1, columnaAnho));
        filters.add(RowFilter.numberFilter(RowFilter.ComparisonType.BEFORE, anhoFiltro2 +1, columnaAnho));
        
        
        this.trsfFiltro.setRowFilter(RowFilter.andFilter(filters));
     }
     
    public void cargarTabla() throws SQLException{
        PeliculaController controller = new PeliculaController();
        
        ArrayList<MovieDAO> listaPeliculaDAO = new ArrayList<MovieDAO>();
        
        listaPeliculaDAO = controller.ListaPeliculaController(this.conector.getConn());
        
        DefaultTableModel modelo = (DefaultTableModel) this.jTableLista.getModel();
        modelo.setRowCount(0);
        
        for (int i = 0; i < listaPeliculaDAO.size(); i++){
            Object[] objeto = {
                listaPeliculaDAO.get(i).getId(),
                listaPeliculaDAO.get(i).getTitulo(),
                listaPeliculaDAO.get(i).getDirector(),
                listaPeliculaDAO.get(i).getAnho(),
                listaPeliculaDAO.get(i).getDuracion(),
                listaPeliculaDAO.get(i).getGenero()
            };
            modelo.addRow(objeto);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInicio = new javax.swing.JPanel();
        jButtonModificarPelicula = new javax.swing.JButton();
        jButtonEliminarPelicula = new javax.swing.JButton();
        jButtonListarPelicula = new javax.swing.JButton();
        jButtonAgregarPelicula = new javax.swing.JButton();
        jButtonInfo = new javax.swing.JButton();
        jPanelContent = new javax.swing.JPanel();
        jPanelAgregar = new javax.swing.JPanel();
        jLabelTituloAgregar = new javax.swing.JLabel();
        jTextFieldDirector = new javax.swing.JTextField();
        jTextFieldGenero = new javax.swing.JTextField();
        jTextFieldTitulo = new javax.swing.JTextField();
        jTextFieldDuracion = new javax.swing.JTextField();
        jTextFieldAnho = new javax.swing.JTextField();
        jLabelDirector = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelGenero = new javax.swing.JLabel();
        jLabelDuracion = new javax.swing.JLabel();
        jLabelAnho = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jPanelEliminar = new javax.swing.JPanel();
        jLabelEliminar = new javax.swing.JLabel();
        jLabelTituloEli = new javax.swing.JLabel();
        jLabelGeneroEli = new javax.swing.JLabel();
        jLabelDirectorEli = new javax.swing.JLabel();
        jLabelAnhoEli = new javax.swing.JLabel();
        jLabelDuracionEli = new javax.swing.JLabel();
        jTextFieldTituloEli = new javax.swing.JTextField();
        jTextFieldGeneroEli = new javax.swing.JTextField();
        jTextFieldAnhoEli = new javax.swing.JTextField();
        jTextFieldDuracionEli = new javax.swing.JTextField();
        jTextFieldDirectorEli = new javax.swing.JTextField();
        jButtonLimpiarEli = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonBuscarEli = new javax.swing.JButton();
        jLabelIdEli = new javax.swing.JLabel();
        jTextFieldIdEli = new javax.swing.JTextField();
        jPanelListar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLista = new javax.swing.JTable();
        jTextFieldFiltro = new javax.swing.JTextField();
        jLabelFiltro = new javax.swing.JLabel();
        jTextFieldAnhoFiltro1 = new javax.swing.JTextField();
        jLabelAnhoFiltrotit = new javax.swing.JLabel();
        jTextFieldAnhoFiltro2 = new javax.swing.JTextField();
        jPanelModificar = new javax.swing.JPanel();
        jButtonModificar = new javax.swing.JButton();
        jLabelTituloModificar = new javax.swing.JLabel();
        jTextFieldDirectorMod = new javax.swing.JTextField();
        jTextFieldGeneroMod = new javax.swing.JTextField();
        jTextFieldTituloMod = new javax.swing.JTextField();
        jTextFieldDuracionMod = new javax.swing.JTextField();
        jTextFieldAnhoMod = new javax.swing.JTextField();
        jLabelDirectorMod = new javax.swing.JLabel();
        jLabelTituloMod = new javax.swing.JLabel();
        jLabelGeneroMod = new javax.swing.JLabel();
        jLabelDuracionMod = new javax.swing.JLabel();
        jLabelAnhoMod = new javax.swing.JLabel();
        jLabelIdMod = new javax.swing.JLabel();
        jTextFieldIdMod = new javax.swing.JTextField();
        jButtonBuscarPelicula1 = new javax.swing.JButton();
        jButtonLimpiarMod = new javax.swing.JButton();
        jPanelInfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanelInicio.setBackground(new java.awt.Color(153, 0, 51));

        jButtonModificarPelicula.setText("Modificar");
        jButtonModificarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarPeliculaActionPerformed(evt);
            }
        });

        jButtonEliminarPelicula.setText("Eliminar");
        jButtonEliminarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarPeliculaActionPerformed(evt);
            }
        });

        jButtonListarPelicula.setText("Listar");
        jButtonListarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarPeliculaActionPerformed(evt);
            }
        });

        jButtonAgregarPelicula.setText("Agregar");
        jButtonAgregarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarPeliculaActionPerformed(evt);
            }
        });

        jButtonInfo.setText("?");

        javax.swing.GroupLayout jPanelInicioLayout = new javax.swing.GroupLayout(jPanelInicio);
        jPanelInicio.setLayout(jPanelInicioLayout);
        jPanelInicioLayout.setHorizontalGroup(
            jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicioLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jButtonAgregarPelicula)
                .addGap(18, 18, 18)
                .addComponent(jButtonModificarPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonEliminarPelicula)
                .addGap(18, 18, 18)
                .addComponent(jButtonListarPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 334, Short.MAX_VALUE)
                .addComponent(jButtonInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanelInicioLayout.setVerticalGroup(
            jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModificarPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminarPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonListarPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAgregarPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanelInicio);
        jPanelInicio.setBounds(0, 0, 800, 70);

        jPanelContent.setLayout(new java.awt.CardLayout());

        jLabelTituloAgregar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelTituloAgregar.setText("agregar peliculas");

        jTextFieldDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDirectorActionPerformed(evt);
            }
        });

        jTextFieldGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGeneroActionPerformed(evt);
            }
        });

        jTextFieldTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTituloActionPerformed(evt);
            }
        });

        jTextFieldDuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDuracionActionPerformed(evt);
            }
        });
        jTextFieldDuracion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDuracionKeyTyped(evt);
            }
        });

        jTextFieldAnho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAnhoActionPerformed(evt);
            }
        });
        jTextFieldAnho.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAnhoKeyTyped(evt);
            }
        });

        jLabelDirector.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelDirector.setText("Director");

        jLabelTitulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelTitulo.setText("Titulo");

        jLabelGenero.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelGenero.setText("Genero");

        jLabelDuracion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelDuracion.setText("Duracion");

        jLabelAnho.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelAnho.setText("Año");

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAgregarLayout = new javax.swing.GroupLayout(jPanelAgregar);
        jPanelAgregar.setLayout(jPanelAgregarLayout);
        jPanelAgregarLayout.setHorizontalGroup(
            jPanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAgregarLayout.createSequentialGroup()
                .addGroup(jPanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAgregarLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAgregarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDirector, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelGenero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAnho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDuracion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAgregarLayout.createSequentialGroup()
                            .addComponent(jLabelTituloAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(288, 288, 288))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAgregarLayout.createSequentialGroup()
                            .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(145, 145, 145)))
                    .addGroup(jPanelAgregarLayout.createSequentialGroup()
                        .addGroup(jPanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAgregarLayout.createSequentialGroup()
                                .addComponent(jButtonLimpiar)
                                .addGap(82, 82, 82)
                                .addComponent(jButtonGuardar))
                            .addComponent(jTextFieldDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAnho, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelAgregarLayout.setVerticalGroup(
            jPanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAgregarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloAgregar)
                .addGap(18, 18, 18)
                .addGroup(jPanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelAnho, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAnho, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldDuracion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDuracion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(jPanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jPanelContent.add(jPanelAgregar, "card2");

        jLabelEliminar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelEliminar.setText("Eliminar peliculas");

        jLabelTituloEli.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelTituloEli.setText("Titulo");

        jLabelGeneroEli.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelGeneroEli.setText("Genero");

        jLabelDirectorEli.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelDirectorEli.setText("Director");

        jLabelAnhoEli.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelAnhoEli.setText("Año");

        jLabelDuracionEli.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelDuracionEli.setText("Duracion");
        jLabelDuracionEli.setToolTipText("");

        jTextFieldTituloEli.setToolTipText("");

        jTextFieldAnhoEli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAnhoEliActionPerformed(evt);
            }
        });
        jTextFieldAnhoEli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAnhoEliKeyTyped(evt);
            }
        });

        jTextFieldDuracionEli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDuracionEliKeyTyped(evt);
            }
        });

        jButtonLimpiarEli.setText("Limpiar");
        jButtonLimpiarEli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarEliActionPerformed(evt);
            }
        });

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.setToolTipText("");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jButtonBuscarEli.setText("Buscar");
        jButtonBuscarEli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarEliActionPerformed(evt);
            }
        });

        jLabelIdEli.setText("ID");

        javax.swing.GroupLayout jPanelEliminarLayout = new javax.swing.GroupLayout(jPanelEliminar);
        jPanelEliminar.setLayout(jPanelEliminarLayout);
        jPanelEliminarLayout.setHorizontalGroup(
            jPanelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEliminarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEliminarLayout.createSequentialGroup()
                        .addComponent(jLabelGeneroEli, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldGeneroEli, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEliminarLayout.createSequentialGroup()
                        .addComponent(jLabelAnhoEli, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAnhoEli, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEliminarLayout.createSequentialGroup()
                        .addComponent(jLabelDirectorEli, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDirectorEli, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEliminarLayout.createSequentialGroup()
                        .addComponent(jLabelDuracionEli, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEliminarLayout.createSequentialGroup()
                                .addComponent(jButtonLimpiarEli, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(147, 147, 147)
                                .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldDuracionEli, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelEliminarLayout.createSequentialGroup()
                        .addGroup(jPanelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTituloEli, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelIdEli, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEliminarLayout.createSequentialGroup()
                                .addComponent(jTextFieldIdEli, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(176, 176, 176)
                                .addComponent(jLabelEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldTituloEli, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(238, Short.MAX_VALUE))
            .addGroup(jPanelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEliminarLayout.createSequentialGroup()
                    .addContainerGap(579, Short.MAX_VALUE)
                    .addComponent(jButtonBuscarEli, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(131, 131, 131)))
        );
        jPanelEliminarLayout.setVerticalGroup(
            jPanelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelEliminarLayout.createSequentialGroup()
                        .addGroup(jPanelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelEliminarLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabelIdEli, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTituloEli, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEliminarLayout.createSequentialGroup()
                        .addComponent(jTextFieldIdEli, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldTituloEli, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(jPanelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelDirectorEli, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDirectorEli, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelEliminarLayout.createSequentialGroup()
                        .addComponent(jLabelGeneroEli, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelAnhoEli, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEliminarLayout.createSequentialGroup()
                        .addComponent(jTextFieldGeneroEli, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldAnhoEli, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelDuracionEli, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDuracionEli, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLimpiarEli, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(126, Short.MAX_VALUE))
            .addGroup(jPanelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelEliminarLayout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addComponent(jButtonBuscarEli, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(413, Short.MAX_VALUE)))
        );

        jPanelContent.add(jPanelEliminar, "card4");

        jTableLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Titulo", "Director", "Año", "Duracion", "Genero"
            }
        ));
        jScrollPane1.setViewportView(jTableLista);

        jTextFieldFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFiltroActionPerformed(evt);
            }
        });
        jTextFieldFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldFiltroKeyReleased(evt);
            }
        });

        jLabelFiltro.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelFiltro.setText("Genero");

        jTextFieldAnhoFiltro1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldAnhoFiltro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAnhoFiltro1ActionPerformed(evt);
            }
        });
        jTextFieldAnhoFiltro1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldAnhoFiltro1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAnhoFiltro1KeyTyped(evt);
            }
        });

        jLabelAnhoFiltrotit.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelAnhoFiltrotit.setText("Año");

        jTextFieldAnhoFiltro2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldAnhoFiltro2KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelListarLayout = new javax.swing.GroupLayout(jPanelListar);
        jPanelListar.setLayout(jPanelListarLayout);
        jPanelListarLayout.setHorizontalGroup(
            jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelListarLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(jPanelListarLayout.createSequentialGroup()
                        .addComponent(jLabelFiltro)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListarLayout.createSequentialGroup()
                                .addComponent(jTextFieldAnhoFiltro1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jTextFieldAnhoFiltro2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(111, 111, 111))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListarLayout.createSequentialGroup()
                                .addComponent(jLabelAnhoFiltrotit)
                                .addGap(162, 162, 162))))))
        );
        jPanelListarLayout.setVerticalGroup(
            jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListarLayout.createSequentialGroup()
                .addGroup(jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelListarLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabelAnhoFiltrotit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldAnhoFiltro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAnhoFiltro2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        jPanelContent.add(jPanelListar, "card5");

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jLabelTituloModificar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelTituloModificar.setText("modificar peliculas");

        jTextFieldDirectorMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDirectorModActionPerformed(evt);
            }
        });

        jTextFieldGeneroMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGeneroModActionPerformed(evt);
            }
        });

        jTextFieldTituloMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTituloModActionPerformed(evt);
            }
        });

        jTextFieldDuracionMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDuracionModActionPerformed(evt);
            }
        });
        jTextFieldDuracionMod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDuracionModKeyTyped(evt);
            }
        });

        jTextFieldAnhoMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAnhoModActionPerformed(evt);
            }
        });
        jTextFieldAnhoMod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAnhoModKeyTyped(evt);
            }
        });

        jLabelDirectorMod.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelDirectorMod.setText("Director");

        jLabelTituloMod.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelTituloMod.setText("Titulo");

        jLabelGeneroMod.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelGeneroMod.setText("Genero");

        jLabelDuracionMod.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelDuracionMod.setText("Duracion");

        jLabelAnhoMod.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelAnhoMod.setText("Año");

        jLabelIdMod.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelIdMod.setText("ID");

        jTextFieldIdMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdModActionPerformed(evt);
            }
        });
        jTextFieldIdMod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIdModKeyTyped(evt);
            }
        });

        jButtonBuscarPelicula1.setText("Buscar");
        jButtonBuscarPelicula1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarPelicula1ActionPerformed(evt);
            }
        });

        jButtonLimpiarMod.setText("Limpiar");
        jButtonLimpiarMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarModActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelModificarLayout = new javax.swing.GroupLayout(jPanelModificar);
        jPanelModificar.setLayout(jPanelModificarLayout);
        jPanelModificarLayout.setHorizontalGroup(
            jPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModificarLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelModificarLayout.createSequentialGroup()
                        .addComponent(jLabelIdMod, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIdMod, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelTituloModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(281, 281, 281))
                    .addGroup(jPanelModificarLayout.createSequentialGroup()
                        .addComponent(jLabelDirectorMod, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDirectorMod, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelModificarLayout.createSequentialGroup()
                        .addComponent(jLabelTituloMod, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldTituloMod, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(188, 188, 188))
                    .addGroup(jPanelModificarLayout.createSequentialGroup()
                        .addGroup(jPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelModificarLayout.createSequentialGroup()
                                .addComponent(jLabelAnhoMod, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAnhoMod, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelModificarLayout.createSequentialGroup()
                                .addComponent(jLabelGeneroMod, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldGeneroMod, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelModificarLayout.createSequentialGroup()
                                .addComponent(jLabelDuracionMod, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDuracionMod, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelModificarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(326, 326, 326))
            .addGroup(jPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelModificarLayout.createSequentialGroup()
                    .addContainerGap(661, Short.MAX_VALUE)
                    .addComponent(jButtonBuscarPelicula1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(73, 73, 73)))
            .addGroup(jPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelModificarLayout.createSequentialGroup()
                    .addGap(125, 125, 125)
                    .addComponent(jButtonLimpiarMod, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(591, Short.MAX_VALUE)))
        );
        jPanelModificarLayout.setVerticalGroup(
            jPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModificarLayout.createSequentialGroup()
                .addGroup(jPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelModificarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTituloModificar)
                            .addComponent(jTextFieldIdMod, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTituloMod, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelModificarLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabelIdMod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTituloMod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelDirectorMod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDirectorMod, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelGeneroMod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldGeneroMod, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelAnhoMod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAnhoMod, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelDuracionMod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDuracionMod, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(jPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelModificarLayout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addComponent(jButtonBuscarPelicula1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(426, Short.MAX_VALUE)))
            .addGroup(jPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelModificarLayout.createSequentialGroup()
                    .addContainerGap(386, Short.MAX_VALUE)
                    .addComponent(jButtonLimpiarMod, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(96, 96, 96)))
        );

        jPanelContent.add(jPanelModificar, "card3");

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanelInfoLayout = new javax.swing.GroupLayout(jPanelInfo);
        jPanelInfo.setLayout(jPanelInfoLayout);
        jPanelInfoLayout.setHorizontalGroup(
            jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoLayout.createSequentialGroup()
                .addGap(373, 373, 373)
                .addComponent(jLabel1)
                .addContainerGap(390, Short.MAX_VALUE))
        );
        jPanelInfoLayout.setVerticalGroup(
            jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoLayout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jLabel1)
                .addContainerGap(303, Short.MAX_VALUE))
        );

        jPanelContent.add(jPanelInfo, "card6");

        getContentPane().add(jPanelContent);
        jPanelContent.setBounds(0, 70, 800, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarPeliculaActionPerformed
        // TODO add your handling code here:
        this.mostrarPanel(jPanelAgregar);
      
    }//GEN-LAST:event_jButtonAgregarPeliculaActionPerformed

    private void jButtonModificarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarPeliculaActionPerformed
        // TODO add your handling code here:
        this.mostrarPanel(jPanelModificar);
    }//GEN-LAST:event_jButtonModificarPeliculaActionPerformed

    private void jButtonEliminarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarPeliculaActionPerformed
        // TODO add your handling code here:
        this.mostrarPanel(jPanelEliminar);
    }//GEN-LAST:event_jButtonEliminarPeliculaActionPerformed

    private void jButtonListarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarPeliculaActionPerformed
    try {
        // TODO add your handling code here:
        cargarTabla();
    } catch (SQLException ex) {
        Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
    }
        this.mostrarPanel(jPanelListar);
        
        
        
    }//GEN-LAST:event_jButtonListarPeliculaActionPerformed

    private void jTextFieldDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDirectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDirectorActionPerformed

    private void jTextFieldGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGeneroActionPerformed

    private void jTextFieldTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTituloActionPerformed

    private void jTextFieldDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDuracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDuracionActionPerformed

    private void jTextFieldAnhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAnhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAnhoActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        // TODO add your handling code here:
        jTextFieldDirector.setText("");
        jTextFieldGenero.setText("");
        jTextFieldTitulo.setText("");
        jTextFieldDuracion.setText("");
        jTextFieldAnho.setText("");
                
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        
        int anho = Integer.parseInt(jTextFieldAnho.getText());
        
        if(this.jTextFieldTitulo.getText().isEmpty() || this.jTextFieldDirector.getText().isEmpty() || this.jTextFieldAnho.getText().isEmpty() || 
                    this.jTextFieldDuracion.getText().isEmpty() || this.jTextFieldGenero.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "faltan campos por completar");
        }else{
            if(anho<1900 || anho>2023){
            JOptionPane.showMessageDialog(this, "ingrese año mayor a 1900 o menor a 2023");
        }else{
            MovieDAO peliculaNueva = new MovieDAO();
            peliculaNueva.setTitulo(jTextFieldTitulo.getText().trim());
            peliculaNueva.setDirector(jTextFieldDirector.getText().trim());
            peliculaNueva.setAnho(Integer.valueOf(jTextFieldAnho.getText().trim()));
            peliculaNueva.setDuracion(Integer.valueOf(jTextFieldDuracion.getText().trim()));
            peliculaNueva.setGenero(jTextFieldGenero.getText().trim());
            
            jTextFieldDirector.setText("");
            jTextFieldGenero.setText("");
            jTextFieldTitulo.setText("");
            jTextFieldDuracion.setText("");
            jTextFieldAnho.setText("");
            
            PeliculaController controlador = new PeliculaController();
            try {
                controlador.agregarPeliculaController(peliculaNueva, this.conector.getConn());
            } catch (SQLException ex) {
                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }
            
                JOptionPane.showMessageDialog(this,"La Pelicula " +peliculaNueva.getTitulo()+ " fue agregada con exito");
        }
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jTextFieldDuracionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDuracionKeyTyped
        // TODO add your handling code here:
        int num = evt.getKeyChar();
        boolean numeros = num >=48 && num <=57;

        if(!numeros){
            evt.consume();
        }

        if(this.jTextFieldDuracion.getText().length()>=3){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldDuracionKeyTyped

    private void jTextFieldAnhoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAnhoKeyTyped
        // TODO add your handling code here:
        int num = evt.getKeyChar();
        boolean numeros = num >=48 && num <=57;

        if(!numeros){
            evt.consume();
        }

        if(this.jTextFieldAnho.getText().length()>=4){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldAnhoKeyTyped

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here:
        int anho = Integer.parseInt(jTextFieldAnhoMod.getText());
        
        if(jTextFieldTituloMod.getText().isEmpty() || jTextFieldDirectorMod.getText().isEmpty() || jTextFieldAnhoMod.getText().isEmpty() || 
                    jTextFieldDuracionMod.getText().isEmpty() || jTextFieldGeneroMod.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "faltan campos por completar");
        }else{
            if(anho<1900 || anho>2023){
            JOptionPane.showMessageDialog(this, "ingrese año mayor a 1900 o menor a 2023");
        }else{
            MovieDAO pelicula = new MovieDAO();
        
        pelicula.setTitulo(jTextFieldTituloMod.getText().trim());
        pelicula.setDirector(jTextFieldDirectorMod.getText().trim());
        pelicula.setAnho(Integer.valueOf(jTextFieldAnhoMod.getText().trim()));
        pelicula.setDuracion(Integer.valueOf(jTextFieldDuracionMod.getText().trim()));
        pelicula.setGenero(jTextFieldGeneroMod.getText().trim());
        pelicula.setId(Integer.valueOf(jTextFieldIdMod.getText().trim()));
        
        jTextFieldDirectorMod.setText("");
        jTextFieldGeneroMod.setText("");
        jTextFieldTituloMod.setText("");
        jTextFieldDuracionMod.setText("");
        jTextFieldAnhoMod.setText("");
        jTextFieldIdMod.setText("");
        
        PeliculaController controlador = new PeliculaController();
        try {
            controlador.modificarPeliculaController(pelicula, this.conector.getConn());
        } catch (SQLException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
            }
            JOptionPane.showMessageDialog(this,"Pelicula modificada con exito");
        }
        
        
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jTextFieldDirectorModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDirectorModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDirectorModActionPerformed

    private void jTextFieldGeneroModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGeneroModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGeneroModActionPerformed

    private void jTextFieldTituloModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTituloModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTituloModActionPerformed

    private void jTextFieldDuracionModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDuracionModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDuracionModActionPerformed

    private void jTextFieldDuracionModKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDuracionModKeyTyped
        // TODO add your handling code here:
        int num = evt.getKeyChar();
        boolean numeros = num >=48 && num <=57;

        if(!numeros){
            evt.consume();
        }

        if(this.jTextFieldDuracionMod.getText().length()>=3){
            evt.consume();
        }
        
    }//GEN-LAST:event_jTextFieldDuracionModKeyTyped

    private void jTextFieldAnhoModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAnhoModActionPerformed
        // TODO add your handling code here:

                  
    }//GEN-LAST:event_jTextFieldAnhoModActionPerformed

    private void jTextFieldAnhoModKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAnhoModKeyTyped
        // TODO add your handling code here:
         int num = evt.getKeyChar();
        boolean numeros = num >=48 && num <=57;

        if(!numeros){
            evt.consume();
        }

        if(this.jTextFieldAnhoMod.getText().length()>=4){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldAnhoModKeyTyped

    private void jTextFieldIdModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdModActionPerformed

    private void jTextFieldIdModKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIdModKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdModKeyTyped

    private void jButtonBuscarPelicula1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarPelicula1ActionPerformed
        // TODO add your handling code here:
        MovieDAO pelicula = new MovieDAO();
        pelicula.setTitulo(jTextFieldTituloMod.getText());
        
        PeliculaController controlador = new PeliculaController();
        
        try {
            boolean flag = controlador.buscarPeliculaController(pelicula, this.conector.getConn());
            
            if (flag == true) {
                jTextFieldDirectorMod.setText(pelicula.getDirector());
                jTextFieldAnhoMod.setText(Integer.toString(pelicula.getAnho()));
                jTextFieldDuracionMod.setText(Integer.toString(pelicula.getDuracion()));
                jTextFieldGeneroMod.setText(pelicula.getGenero());
                jTextFieldIdMod.setText(Integer.toString(pelicula.getId()));
 
            } else {
                JOptionPane.showMessageDialog(null, "No se encontro la pelicula " + pelicula.getTitulo());
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        System.out.println(pelicula.toString());
    }//GEN-LAST:event_jButtonBuscarPelicula1ActionPerformed

    private void jButtonLimpiarModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarModActionPerformed
        // TODO add your handling code here:
        
        jTextFieldDirectorMod.setText("");
        jTextFieldGeneroMod.setText("");
        jTextFieldTituloMod.setText("");
        jTextFieldDuracionMod.setText("");
        jTextFieldAnhoMod.setText("");
        jTextFieldIdMod.setText("");
        
    }//GEN-LAST:event_jButtonLimpiarModActionPerformed

    private void jButtonBuscarEliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarEliActionPerformed
        // TODO add your handling code here:
        MovieDAO pelicula = new MovieDAO();
        pelicula.setTitulo(jTextFieldTituloEli.getText());
        
        PeliculaController controlador = new PeliculaController();
        
        try {
            boolean flag = controlador.buscarPeliculaController(pelicula, this.conector.getConn());
            
            if (flag == true) {
                jTextFieldDirectorEli.setText(pelicula.getDirector());
                jTextFieldAnhoEli.setText(Integer.toString(pelicula.getAnho()));
                jTextFieldDuracionEli.setText(Integer.toString(pelicula.getDuracion()));
                jTextFieldGeneroEli.setText(pelicula.getGenero());
                jTextFieldIdEli.setText(Integer.toString(pelicula.getId()));
                  
 
            } else {
                JOptionPane.showMessageDialog(null, "No se encontro la pelicula " + pelicula.getTitulo());
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        System.out.println(pelicula.toString());
        
    }//GEN-LAST:event_jButtonBuscarEliActionPerformed

    private void jButtonLimpiarEliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarEliActionPerformed
        // TODO add your handling code here:
        jTextFieldDirectorEli.setText("");
        jTextFieldGeneroEli.setText("");
        jTextFieldTituloEli.setText("");
        jTextFieldDuracionEli.setText("");
        jTextFieldAnhoEli.setText("");
        jTextFieldIdEli.setText("");
    }//GEN-LAST:event_jButtonLimpiarEliActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
        int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro?", "Alerta!", JOptionPane.YES_NO_OPTION);
        int anho = Integer.parseInt(jTextFieldAnhoEli.getText());
        
        if(jTextFieldTituloEli.getText().isEmpty() || jTextFieldDirectorEli.getText().isEmpty() || jTextFieldAnhoEli.getText().isEmpty() || 
                    jTextFieldDuracionEli.getText().isEmpty() || jTextFieldGeneroEli.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "faltan campos por completar");
        }else{
                if(resp == JOptionPane.YES_OPTION){
            MovieDAO pelicula = new MovieDAO();
        
        pelicula.setTitulo(jTextFieldTituloEli.getText());
        pelicula.setDirector(jTextFieldDirectorEli.getText());
        pelicula.setAnho(Integer.valueOf(jTextFieldAnhoEli.getText()));
        pelicula.setDuracion(Integer.valueOf(jTextFieldDuracionEli.getText()));
        pelicula.setGenero(jTextFieldGeneroEli.getText());
        pelicula.setId(Integer.valueOf(jTextFieldIdEli.getText()));
        
                jTextFieldDirectorEli.setText("");
                jTextFieldGeneroEli.setText("");
                jTextFieldTituloEli.setText("");
                jTextFieldDuracionEli.setText("");
                jTextFieldAnhoEli.setText("");
                jTextFieldIdEli.setText("");
        
        PeliculaController controlador = new PeliculaController();
        try {
            controlador.eliminarPeliculaController(pelicula, this.conector.getConn());
        } catch (SQLException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "se elimino la pelicula correctamente");
            }else{
                    JOptionPane.showMessageDialog(this, "no se elimino la pelicula");
                }
        }
        
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jTextFieldAnhoEliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAnhoEliActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_jTextFieldAnhoEliActionPerformed

    private void jTextFieldAnhoEliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAnhoEliKeyTyped
        // TODO add your handling code here:
        int num = evt.getKeyChar();
        boolean numeros = num >=48 && num <=57;

        if(!numeros){
            evt.consume();
        }

        if(this.jTextFieldAnhoEli.getText().length()>=4){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldAnhoEliKeyTyped

    private void jTextFieldDuracionEliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDuracionEliKeyTyped
        // TODO add your handling code here:
        int num = evt.getKeyChar();
        boolean numeros = num >=48 && num <=57;

        if(!numeros){
            evt.consume();
        }

        if(this.jTextFieldDuracionEli.getText().length()>=4){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldDuracionEliKeyTyped

    private void jTextFieldFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFiltroActionPerformed

    private void jTextFieldFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFiltroKeyReleased
        // TODO add your handling code here:
        trsfFiltro = new TableRowSorter(jTableLista.getModel());
        filtro();
        jTableLista.setRowSorter(trsfFiltro);
    }//GEN-LAST:event_jTextFieldFiltroKeyReleased

    private void jTextFieldAnhoFiltro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAnhoFiltro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAnhoFiltro1ActionPerformed

    private void jTextFieldAnhoFiltro1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAnhoFiltro1KeyReleased
        // TODO add your handling code here:
        trsfFiltro = new TableRowSorter(jTableLista.getModel());
        filtro();
        jTableLista.setRowSorter(trsfFiltro);
    }//GEN-LAST:event_jTextFieldAnhoFiltro1KeyReleased

    private void jTextFieldAnhoFiltro1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAnhoFiltro1KeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldAnhoFiltro1KeyTyped

    private void jTextFieldAnhoFiltro2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAnhoFiltro2KeyReleased
        // TODO add your handling code here:
        trsfFiltro = new TableRowSorter(jTableLista.getModel());
        filtro();
        jTableLista.setRowSorter(trsfFiltro);
    }//GEN-LAST:event_jTextFieldAnhoFiltro2KeyReleased

   
    /**
     * @param args the command line arguments
     */
   
  
    
    private void mostrarPanel(JPanel p){
       jPanelContent.removeAll();
       jPanelContent.add(p);
       jPanelContent.repaint();
       jPanelContent.revalidate();
    }

    protected Connection conexionOCI;
    protected ConectorBD conector;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarPelicula;
    private javax.swing.JButton jButtonBuscarEli;
    private javax.swing.JButton jButtonBuscarPelicula1;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonEliminarPelicula;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonInfo;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonLimpiarEli;
    private javax.swing.JButton jButtonLimpiarMod;
    private javax.swing.JButton jButtonListarPelicula;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonModificarPelicula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAnho;
    private javax.swing.JLabel jLabelAnhoEli;
    private javax.swing.JLabel jLabelAnhoFiltrotit;
    private javax.swing.JLabel jLabelAnhoMod;
    private javax.swing.JLabel jLabelDirector;
    private javax.swing.JLabel jLabelDirectorEli;
    private javax.swing.JLabel jLabelDirectorMod;
    private javax.swing.JLabel jLabelDuracion;
    private javax.swing.JLabel jLabelDuracionEli;
    private javax.swing.JLabel jLabelDuracionMod;
    private javax.swing.JLabel jLabelEliminar;
    private javax.swing.JLabel jLabelFiltro;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelGeneroEli;
    private javax.swing.JLabel jLabelGeneroMod;
    private javax.swing.JLabel jLabelIdEli;
    private javax.swing.JLabel jLabelIdMod;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTituloAgregar;
    private javax.swing.JLabel jLabelTituloEli;
    private javax.swing.JLabel jLabelTituloMod;
    private javax.swing.JLabel jLabelTituloModificar;
    private javax.swing.JPanel jPanelAgregar;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JPanel jPanelEliminar;
    private javax.swing.JPanel jPanelInfo;
    private javax.swing.JPanel jPanelInicio;
    private javax.swing.JPanel jPanelListar;
    private javax.swing.JPanel jPanelModificar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLista;
    private javax.swing.JTextField jTextFieldAnho;
    private javax.swing.JTextField jTextFieldAnhoEli;
    private javax.swing.JTextField jTextFieldAnhoFiltro1;
    private javax.swing.JTextField jTextFieldAnhoFiltro2;
    private javax.swing.JTextField jTextFieldAnhoMod;
    private javax.swing.JTextField jTextFieldDirector;
    private javax.swing.JTextField jTextFieldDirectorEli;
    private javax.swing.JTextField jTextFieldDirectorMod;
    private javax.swing.JTextField jTextFieldDuracion;
    private javax.swing.JTextField jTextFieldDuracionEli;
    private javax.swing.JTextField jTextFieldDuracionMod;
    private javax.swing.JTextField jTextFieldFiltro;
    private javax.swing.JTextField jTextFieldGenero;
    private javax.swing.JTextField jTextFieldGeneroEli;
    private javax.swing.JTextField jTextFieldGeneroMod;
    private javax.swing.JTextField jTextFieldIdEli;
    private javax.swing.JTextField jTextFieldIdMod;
    private javax.swing.JTextField jTextFieldTitulo;
    private javax.swing.JTextField jTextFieldTituloEli;
    private javax.swing.JTextField jTextFieldTituloMod;
    // End of variables declaration//GEN-END:variables
}
